// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * 域名服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchDeleteDomainsByNames 根据域名名称批量删除
 * @param {string[]} domainNames
 * @returns {$CancellablePromise<void>}
 */
export function BatchDeleteDomainsByNames(domainNames) {
    return $Call.ByID(140590482, domainNames);
}

/**
 * 批量扫描
 * @param {string[]} domains
 * @returns {$CancellablePromise<void>}
 */
export function BatchRefreshDomains(domains) {
    return $Call.ByID(2738034909, domains);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckAutoStartStatus() {
    return $Call.ByID(1791036316);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DownloadDomainTemplate() {
    return $Call.ByID(2611316749);
}

/**
 * 获取本地版本号
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(639806916);
}

/**
 * GetDashboardStats 获取仪表盘综合统计数据
 * @returns {$CancellablePromise<$models.DashboardStats>}
 */
export function GetDashboardStats() {
    return $Call.ByID(1215967890).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetDomainList 获取所有监控域名列表
 * @returns {$CancellablePromise<$models.DomainInfo[]>}
 */
export function GetDomainList() {
    return $Call.ByID(1435388225).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetMpCode() {
    return $Call.ByID(2124373057);
}

/**
 * 获取远端版本号
 * @returns {$CancellablePromise<model$0.UpdateInfo>}
 */
export function GetRemoteVersion() {
    return $Call.ByID(419737025).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetScheduleConfig 供前端调用以加载当前配置
 * @returns {$CancellablePromise<model$0.ScheduleConfig>}
 */
export function GetScheduleConfig() {
    return $Call.ByID(3963885558).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * 初始化系统状态
 * @param {string} devID
 * @returns {$CancellablePromise<void>}
 */
export function InitAppState(devID) {
    return $Call.ByID(2263964957, devID);
}

/**
 * 是否首次运行
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFirstRun() {
    return $Call.ByID(3913795232);
}

/**
 * RebuildIndex 当 Domains 切片发生增删或扩容时，必须调用此函数
 * @returns {$CancellablePromise<void>}
 */
export function RebuildIndex() {
    return $Call.ByID(735947138);
}

/**
 * @param {string[]} domains
 * @returns {$CancellablePromise<void>}
 */
export function SaveImportedDomains(domains) {
    return $Call.ByID(3737910523, domains);
}

/**
 * SaveScheduleConfig 供前端调用以保存通知策略
 * @param {model$0.ScheduleConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveScheduleConfig(config) {
    return $Call.ByID(1183606061, config);
}

/**
 * SaveWebhook 保存配置到 Store 并持久化
 * @param {string} platform
 * @param {model$0.WebhookModel} m
 * @returns {$CancellablePromise<void>}
 */
export function SaveWebhook(platform, m) {
    return $Call.ByID(3373931611, platform, m);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectDomainFile() {
    return $Call.ByID(1923186557);
}

/**
 * @param {boolean} state
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoStart(state) {
    return $Call.ByID(1383603110, state);
}

/**
 * 客户端初始化，创建加密数据文件
 * @param {string} password
 * @returns {$CancellablePromise<void>}
 */
export function SetPassword(password) {
    return $Call.ByID(1296111848, password);
}

/**
 * TestWebhook 供前端调用的测试接口
 * @param {string} platform
 * @param {model$0.WebhookModel} m
 * @returns {$CancellablePromise<void>}
 */
export function TestWebhook(platform, m) {
    return $Call.ByID(141486924, platform, m);
}

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.VerifyResult>}
 */
export function VerifyDomainFile(filePath) {
    return $Call.ByID(1861258544, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DashboardStats.createFrom;
const $$createType1 = $models.DomainInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.UpdateInfo.createFrom;
const $$createType4 = model$0.ScheduleConfig.createFrom;
const $$createType5 = $models.VerifyResult.createFrom;
