// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DashboardStats 仪表盘统计数据结构
 */
export class DashboardStats {
    /**
     * Creates a new DashboardStats instance.
     * @param {Partial<DashboardStats>} [$$source = {}] - The source object to create the DashboardStats.
     */
    constructor($$source = {}) {
        if (!("currentTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentTotal"] = 0;
        }
        if (!("maxLimit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxLimit"] = 0;
        }
        if (!("alertCount" in $$source)) {
            /**
             * --- 细化统计维度 ---
             * 总预警数 (进入阈值或扫描失败)
             * @member
             * @type {number}
             */
            this["alertCount"] = 0;
        }
        if (!("sslAlertCount" in $$source)) {
            /**
             * 仅证书预警/失败
             * @member
             * @type {number}
             */
            this["sslAlertCount"] = 0;
        }
        if (!("domainAlertCount" in $$source)) {
            /**
             * 仅域名预警/失败
             * @member
             * @type {number}
             */
            this["domainAlertCount"] = 0;
        }
        if (!("expiredCount" in $$source)) {
            /**
             * 已过期总数 (SSL过期或域名过期)
             * @member
             * @type {number}
             */
            this["expiredCount"] = 0;
        }
        if (!("notifyThreshold" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["notifyThreshold"] = 0;
        }
        if (!("notifyTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notifyTime"] = "";
        }
        if (!("lastScanTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastScanTime"] = "";
        }
        if (!("nextScanTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nextScanTime"] = "";
        }
        if (!("webhookStatus" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: boolean }}
             */
            this["webhookStatus"] = {};
        }
        if (!("updatedFields" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: boolean }}
             */
            this["updatedFields"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DashboardStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DashboardStats}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("webhookStatus" in $$parsedSource) {
            $$parsedSource["webhookStatus"] = $$createField10_0($$parsedSource["webhookStatus"]);
        }
        if ("updatedFields" in $$parsedSource) {
            $$parsedSource["updatedFields"] = $$createField11_0($$parsedSource["updatedFields"]);
        }
        return new DashboardStats(/** @type {Partial<DashboardStats>} */($$parsedSource));
    }
}

/**
 * 返回前端域名证书信息
 */
export class DomainInfo {
    /**
     * Creates a new DomainInfo instance.
     * @param {Partial<DomainInfo>} [$$source = {}] - The source object to create the DomainInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * ID
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("domain" in $$source)) {
            /**
             * 域名
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("sslStatus" in $$source)) {
            /**
             * --- 证书状态 (SSL) ---
             * valid, warning, expired, error
             * @member
             * @type {string}
             */
            this["sslStatus"] = "";
        }
        if (!("sslDate" in $$source)) {
            /**
             * 证书到期日期 (2024-12-31)
             * @member
             * @type {string}
             */
            this["sslDate"] = "";
        }
        if (!("sslRemain" in $$source)) {
            /**
             * 证书剩余天数
             * @member
             * @type {number}
             */
            this["sslRemain"] = 0;
        }
        if (!("sslError" in $$source)) {
            /**
             * 证书扫描的具体报错
             * @member
             * @type {string}
             */
            this["sslError"] = "";
        }
        if (!("domainStatus" in $$source)) {
            /**
             * --- 域名状态 (Whois) ---
             * active, expired, error
             * @member
             * @type {string}
             */
            this["domainStatus"] = "";
        }
        if (!("domainDate" in $$source)) {
            /**
             * 域名到期日期 (2025-06-01)
             * @member
             * @type {string}
             */
            this["domainDate"] = "";
        }
        if (!("domainRemain" in $$source)) {
            /**
             * 域名剩余天数
             * @member
             * @type {number}
             */
            this["domainRemain"] = 0;
        }
        if (!("domainError" in $$source)) {
            /**
             * Whois 查询的具体报错
             * @member
             * @type {string}
             */
            this["domainError"] = "";
        }
        if (!("lastCheckAt" in $$source)) {
            /**
             * --- 综合信息 ---
             * 上次成功更新的时间
             * @member
             * @type {string}
             */
            this["lastCheckAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DomainInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DomainInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DomainInfo(/** @type {Partial<DomainInfo>} */($$parsedSource));
    }
}

/**
 * 验证结果
 */
export class VerifyResult {
    /**
     * Creates a new VerifyResult instance.
     * @param {Partial<VerifyResult>} [$$source = {}] - The source object to create the VerifyResult.
     */
    constructor($$source = {}) {
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["valid"] = [];
        }
        if (!("duplicate" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["duplicate"] = [];
        }
        if (!("invalid" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["invalid"] = [];
        }
        if (!("currentTotal" in $$source)) {
            /**
             * 当前已存在数量
             * @member
             * @type {number}
             */
            this["currentTotal"] = 0;
        }
        if (!("remainingQuota" in $$source)) {
            /**
             * 剩余可用名额
             * @member
             * @type {number}
             */
            this["remainingQuota"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VerifyResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VerifyResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("valid" in $$parsedSource) {
            $$parsedSource["valid"] = $$createField0_0($$parsedSource["valid"]);
        }
        if ("duplicate" in $$parsedSource) {
            $$parsedSource["duplicate"] = $$createField1_0($$parsedSource["duplicate"]);
        }
        if ("invalid" in $$parsedSource) {
            $$parsedSource["invalid"] = $$createField2_0($$parsedSource["invalid"]);
        }
        return new VerifyResult(/** @type {Partial<VerifyResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
