// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * 调度配置
 */
export class ScheduleConfig {
    /**
     * Creates a new ScheduleConfig instance.
     * @param {Partial<ScheduleConfig>} [$$source = {}] - The source object to create the ScheduleConfig.
     */
    constructor($$source = {}) {
        if (!("lastNotifyDate" in $$source)) {
            /**
             * 最近一次通知时间
             * 记录上次发送日期，如 "2026-01-24"
             * @member
             * @type {string}
             */
            this["lastNotifyDate"] = "";
        }
        if (!("lastFullScanAt" in $$source)) {
            /**
             * 扫描控制
             * 上次全量扫描时间戳
             * @member
             * @type {number}
             */
            this["lastFullScanAt"] = 0;
        }
        if (!("notifyTime" in $$source)) {
            /**
             * 通知设置
             * 每日通知时间点，如 "10:00"
             * @member
             * @type {string}
             */
            this["notifyTime"] = "";
        }
        if (!("notifyThreshold" in $$source)) {
            /**
             * 提前告警阈值（天），如 30
             * @member
             * @type {number}
             */
            this["notifyThreshold"] = 0;
        }
        if (!("enableNotify" in $$source)) {
            /**
             * 是否开启机器人通知
             * @member
             * @type {boolean}
             */
            this["enableNotify"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScheduleConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScheduleConfig(/** @type {Partial<ScheduleConfig>} */($$parsedSource));
    }
}

/**
 * 更新信息
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }
        if (!("updateLog" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updateLog"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

/**
 * webhook模型
 */
export class WebhookModel {
    /**
     * Creates a new WebhookModel instance.
     * @param {Partial<WebhookModel>} [$$source = {}] - The source object to create the WebhookModel.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "dingtalk" 或 "wechat"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * Webhook 完整地址
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("secret" in $$source)) {
            /**
             * 仅钉钉加签使用
             * @member
             * @type {string}
             */
            this["secret"] = "";
        }
        if (!("enable" in $$source)) {
            /**
             * 是否启用
             * @member
             * @type {boolean}
             */
            this["enable"] = false;
        }
        if (!("updated_at" in $$source)) {
            /**
             * 更新时间
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebhookModel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebhookModel}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebhookModel(/** @type {Partial<WebhookModel>} */($$parsedSource));
    }
}
